insert into employees (name, display_order) values
('Alexandre', 1),
('Anaelle', 2),
('Audrey', 3),
('Carolle', 4),
('Celine', 5),
('Christophe', 6),
('Cloé', 7),
('Cyril', 8),
('Elodie', 9),
('Fabrice', 10),
('Franck', 11),
('Francois', 12),
('Gael', 13),
('Jacques', 14),
('Julien', 15),
('Laura', 16),
('Laura Ja', 17),
('Léa', 18),
('Ludivine', 19),
('Lydie', 20),
('Manuella', 21),
('Marc', 22),
('Marie', 23),
('Maxime', 24),
('Pascal', 25),
('Prescillia', 26),
('Quentin', 27),
('Rachel', 28),
('Romain', 29),
('Sabrina', 30),
('Sandrine', 31),
('Stephane', 32),
('Thibaut', 33),
('Valentin', 34),
('Vanessa', 35),
('Virginie', 36),
('Virginie Moiss', 37),
('Yasmina', 38),
('Yolande', 39)
on conflict (name) do update set display_order = excluded.display_order;

insert into matches (id, group_name, team_a, team_b, position) values
('A1', 'A', 'Mexique', 'Afrique du Sud', 1),
('A2', 'A', 'Corée du Sud', 'Tchéquie', 2),
('A3', 'A', 'Tchéquie', 'Afrique du Sud', 3),
('A4', 'A', 'Mexique', 'Corée du Sud', 4),
('A5', 'A', 'Tchéquie', 'Mexique', 5),
('A6', 'A', 'Afrique du Sud', 'Corée du Sud', 6),
('B1', 'B', 'Canada', 'Bosnie-Herz', 7),
('B2', 'B', 'Qatar', 'Suisse', 8),
('B3', 'B', 'Suisse', 'Bosnie-Herz', 9),
('B4', 'B', 'Canada', 'Qatar', 10),
('B5', 'B', 'Suisse', 'Canada', 11),
('B6', 'B', 'Bosnie-Herz', 'Qatar', 12),
('C1', 'C', 'Brésil', 'Maroc', 13),
('C2', 'C', 'Haiti', 'Ecosse', 14),
('C3', 'C', 'Ecosse', 'Maroc', 15),
('C4', 'C', 'Brésil', 'Haiti', 16),
('C5', 'C', 'Ecosse', 'Brésil', 17),
('C6', 'C', 'Maroc', 'Haiti', 18),
('D1', 'D', 'USA', 'Paraguay', 19),
('D2', 'D', 'Australie', 'Turquie', 20),
('D3', 'D', 'USA', 'Australie', 21),
('D4', 'D', 'Turquie', 'Paraguay', 22),
('D5', 'D', 'Turquie', 'USA', 23),
('D6', 'D', 'Paraguay', 'Australie', 24),
('E1', 'E', 'Allemagne', 'Curacao', 25),
('E2', 'E', 'Côte d''Ivoire', 'Equateur', 26),
('E3', 'E', 'Allemagne', 'Côte d''Ivoire', 27),
('E4', 'E', 'Equateur', 'Curacao', 28),
('E5', 'E', 'Equateur', 'Allemagne', 29),
('E6', 'E', 'Curacao', 'Côte d''Ivoire', 30),
('F1', 'F', 'Pays-Bas', 'Japon', 31),
('F2', 'F', 'Suède', 'Tunisie', 32),
('F3', 'F', 'Pays-Bas', 'Suède', 33),
('F4', 'F', 'Tunisie', 'Japon', 34),
('F5', 'F', 'Tunisie', 'Pays-Bas', 35),
('F6', 'F', 'Japon', 'Suède', 36),
('G1', 'G', 'Belgique', 'Egypte', 37),
('G2', 'G', 'Iran', 'Nouvelle Zelande', 38),
('G3', 'G', 'Belgique', 'Iran', 39),
('G4', 'G', 'Nouvelle Zelande', 'Egypte', 40),
('G5', 'G', 'Nouvelle Zelande', 'Belgique', 41),
('G6', 'G', 'Egypte', 'Iran', 42),
('H1', 'H', 'Espagne', 'Cap-Vert', 43),
('H2', 'H', 'Arabie Saoudite', 'Uruguay', 44),
('H3', 'H', 'Espagne', 'Arabie Saoudite', 45),
('H4', 'H', 'Uruguay', 'Cap-Vert', 46),
('H5', 'H', 'Uruguay', 'Espagne', 47),
('H6', 'H', 'Cap-Vert', 'Arabie Saoudite', 48),
('I1', 'I', 'France', 'Sénégal', 49),
('I2', 'I', 'Irak', 'Norvège', 50),
('I3', 'I', 'France', 'Irak', 51),
('I4', 'I', 'Norvège', 'Sénégal', 52),
('I5', 'I', 'Norvège', 'France', 53),
('I6', 'I', 'Sénégal', 'Irak', 54),
('J1', 'J', 'Argentine', 'Algérie', 55),
('J2', 'J', 'Autriche', 'Jordanie', 56),
('J3', 'J', 'Argentine', 'Autriche', 57),
('J4', 'J', 'Jordanie', 'Algérie', 58),
('J5', 'J', 'Jordanie', 'Argentine', 59),
('J6', 'J', 'Algérie', 'Autriche', 60),
('K1', 'K', 'Portugal', 'Congo', 61),
('K2', 'K', 'Ouzbekistan', 'Colombie', 62),
('K3', 'K', 'Portugal', 'Ouzbekistan', 63),
('K4', 'K', 'Colombie', 'Congo', 64),
('K5', 'K', 'Colombie', 'Portugal', 65),
('K6', 'K', 'Congo', 'Ouzbekistan', 66),
('L1', 'L', 'Angleterre', 'Croatie', 67),
('L2', 'L', 'Ghana', 'Panama', 68),
('L3', 'L', 'Angleterre', 'Ghana', 69),
('L4', 'L', 'Panama', 'Croatie', 70),
('L5', 'L', 'Panama', 'Angleterre', 71),
('L6', 'L', 'Croatie', 'Ghana', 72)
on conflict (id) do update set group_name=excluded.group_name, team_a=excluded.team_a, team_b=excluded.team_b, position=excluded.position;