// Correspondance entre les noms d'équipes renvoyés par l'API football-data.org
// (en anglais) et les noms utilisés dans ta base Supabase (en français).
//
// >>> À VÉRIFIER / AJUSTER <<<
// Si la synchronisation signale des équipes "non mappées", ajoute simplement
// une ligne ici : "Nom exact renvoyé par l'API": "Nom exact dans ta base".
// Plusieurs alias peuvent pointer vers le même nom français.

module.exports = {
  "Mexico": "Mexique",
  "South Africa": "Afrique du Sud",
  "South Korea": "Corée du Sud",
  "Korea Republic": "Corée du Sud",
  "Czechia": "Tchéquie",
  "Czech Republic": "Tchéquie",
  "Canada": "Canada",
  "Bosnia and Herzegovina": "Bosnie-Herz",
  "Bosnia-Herzegovina": "Bosnie-Herz",
  "Qatar": "Qatar",
  "Switzerland": "Suisse",
  "Brazil": "Brésil",
  "Morocco": "Maroc",
  "Haiti": "Haiti",
  "Scotland": "Ecosse",
  "United States": "USA",
  "USA": "USA",
  "Paraguay": "Paraguay",
  "Australia": "Australie",
  "Turkey": "Turquie",
  "Türkiye": "Turquie",
  "Germany": "Allemagne",
  "Curacao": "Curacao",
  "Curaçao": "Curacao",
  "Ivory Coast": "Côte d'Ivoire",
  "Cote d'Ivoire": "Côte d'Ivoire",
  "Côte d'Ivoire": "Côte d'Ivoire",
  "Ecuador": "Equateur",
  "Netherlands": "Pays-Bas",
  "Japan": "Japon",
  "Sweden": "Suède",
  "Tunisia": "Tunisie",
  "Belgium": "Belgique",
  "Egypt": "Egypte",
  "Iran": "Iran",
  "IR Iran": "Iran",
  "New Zealand": "Nouvelle Zelande",
  "Spain": "Espagne",
  "Cape Verde": "Cap-Vert",
  "Cabo Verde": "Cap-Vert",
  "Saudi Arabia": "Arabie Saoudite",
  "Uruguay": "Uruguay",
  "France": "France",
  "Senegal": "Sénégal",
  "Iraq": "Irak",
  "Norway": "Norvège",
  "Argentina": "Argentine",
  "Algeria": "Algérie",
  "Austria": "Autriche",
  "Jordan": "Jordanie",
  "Portugal": "Portugal",
  "Congo": "Congo",
  "Congo DR": "Congo",
  "DR Congo": "Congo",
  "Uzbekistan": "Ouzbekistan",
  "Colombia": "Colombie",
  "England": "Angleterre",
  "Croatia": "Croatie",
  "Ghana": "Ghana",
  "Panama": "Panama"
};
